import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import GlobalHeader from '../_components/GlobalHeader'; 
import GlobalFooter from '../_components/GlobalFooter';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="wrapper">
          <GlobalHeader />
          <main className="content">
            {children}
          </main>
          <GlobalFooter />
        </div>
      </body>
    </html>
  );
}
